version: "3"
services:
  sql:
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: M@EtNGy7
      MSSQL_PID: Express
    image: mcr.microsoft.com/mssql/server:2019-latest
  todo:
    ports:
      - "80:80"
    build:
      context: .
      dockerfile: TodoApp.Api/Dockerfile
  nginx:
    ports:
      - "8080:8080"
    build:
      context: Nginx
      dockerfile: Dockerfile

#  nginx: 
#    image: nginx:latest
#    container_name: production_nginx
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf
#    ports:
#      - 8080:8080

#  redis:
#    image: "redis:alpine"

